# 功能说明: Docker Compose GPU 版覆盖配置文件。此文件扩展了 `docker-compose.yml`，为 MAESTRO 应用程序的后端、文档处理器和命令行工具增加了 NVIDIA GPU 支持。

# GPU 启用覆盖配置
# 此文件扩展 docker-compose.yml，为 NVIDIA GPU 提供 GPU 支持

services:
  backend:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${BACKEND_GPU_DEVICE:-0}']
              capabilities: [gpu]

  doc-processor:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${DOC_PROCESSOR_GPU_DEVICE:-0}']
              capabilities: [gpu]

  cli:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${CLI_GPU_DEVICE:-0}']
              capabilities: [gpu]

  # 可选: 取消注释以添加对本地 LLM 的 GPU 支持
  # local-llm:
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]